name: Check OTC Page Availability

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches: [ "main" ]

jobs:
  verify-content:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Make POST Request to API
        id: api-call
        run: |
          const http = require('@actions/http-client');
          const response = await http.post('http://your-api-url.com', JSON.stringify({ /* Your request body */ }));
          console.log(response.statusCode);
          console.log(response.result);
      
    #   - name: Wait for 1 Minute
    #     run: |
    #       sleep 60  # Wait for 1 minute

      - name: Open Web Page and Verify Content
        id: verify-page
        run: |
          const puppeteer = require('puppeteer-core');
          const browser = await puppeteer.launch();
          const page = await browser.newPage();
          await page.goto('https://www.google.com');
          const content = await page.content();
          console.log(content.includes('test Expected Content'));
