name: Check OTC Page Availability

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches: [ "main" ]

jobs:
  verify-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Call POST API
        run: |
          curl -X GET https://www.google.com
        # Replace the URL and payload with your actual POST API endpoint and payload

      - name: Open Web Page and Verify Content
        uses: dramforever/puppeteer-action@v1
        with:
          args: |
            async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('http://example.com'); // Replace with your page URL
              await new Promise(resolve => setTimeout(resolve, 60000)); // Wait for 1 minute
              const content = await page.content();
              console.log(content.includes('Expected Content')); // Verify expected content
              await browser.close();
            }
